// utils/enum/subcategoryEnum.ts

// ===== Culture Subcategories =====
export const CultureSubcategories = {
    personnel: [
        "integrity",
        "innovation",
        "customer-focus",
        "quality",
        "diversity-handling",
        "adaptability",
        "cultural-awareness",
        "flexibility",
        "analytical-skills",
        "empathy",
    ],
    participants: [
        "engagement",
        "accessibility",
        "collaboration",
        "leadership-support",
        "feedback",
        "involvement",
        "empowerment",
        "inclusive-communication",
        "joint-learning",
        "representation",
    ],
    perception: [
        "reliability",
        "authenticity",
        "transparency",
        "trust",
        "appreciation",
        "accessibility",
        "positive-experience",
        "visibility",
        "empathy",
        "inclusive-experience",
    ],
    price: [
        "willingness-to-invest",
        "allocation-of-time",
        "workforce-and-expertise",
        "training-and-development",
        "cost-control",
        "grants-and-financial-support",
        "budget-management",
        "long-term-investment-plan",
        "flexibility-in-allocation",
        "accountability",
    ],
    place: [
        "accessibility",
        "equality-in-facilities",
        "privacy-and-comfort",
        "virtual-inclusion",
        "cultural-symbolism",
        "flexibility-in-work-hours",
        "equal-treatment",
        "inclusive-design",
        "safety",
        "applicability",
    ],
    priority: [
        "strategic-focus",
        "prioritization-of-d-and-i-goals",
        "leadership-commitment",
        "resource-allocation",
        "integration-into-performance-systems",
        "organizational-awareness",
        "engagement-and-participation",
        "adaptability-of-priorities",
        "continuity-and-perseverance",
        "evaluation-and-adjustment",
    ],
    product: [
        "accessibility",
        "usability",
        "diversity-in-design",
        "inclusive-language",
        "adaptability",
        "affordability",
        "environmental-awareness",
        "cultural-sensitivity",
        "gender-neutrality",
        "innovation",
    ],
    procedure: [
        "equality",
        "d-and-i-integration",
        "anti-discrimination",
        "inclusive-recruitment",
        "accessibility",
        "affirmative-action",
        "training",
        "feedback-mechanism",
        "fair-evaluation",
        "grievance-handling",
    ],
    promotion: [
        "transparency",
        "brand-reputation",
        "inclusive-campaigns",
        "customer-focused-approach",
        "positive-pr",
        "engagement",
        "social-media-activity",
        "ambassadors",
        "events-and-speakers",
        "partnering-with-diversity-initiatives",
    ],
    performance: [
        "performance-indicators-kpis",
        "goals-and-results",
        "success-ratio",
        "feedback-analysis",
        "inclusion-rate",
        "satisfaction-ratings",
        "turnover-rates",
        "inclusive-training",
        "accountability",
        "areas-for-improvement",
    ],
} as const;

// ===== Swot Subcategories =====
export const SwotSubcategories = {
    "goal-oriented-decision-makers": [
        "result-orientation",
        "efficiency-and-time-management",
        "independence",
        "quick-decision-making",
        "performance-orientation",
        "competitiveness",
        "goal-orientation",
        "risk-taking",
        "innovation-orientation",
        "dominance",
    ],
    "harmonious-collaborators": [
        "harmony-and-respect",
        "emotional-self-control",
        "indirect-communication",
        "patience",
        "long-term-relationships",
        "caring-for-others",
        "social-justice",
        "equality",
        "respect-for-hierarchy",
        "reconciliation",
    ],
    "analytical-strategists": [
        "long-term-planning",
        "systematic-thinking",
        "responsibility",
        "rules-and-procedures",
        "efficiency",
        "risk-analysis",
        "strategic-approach",
        "technology-orientation",
        "creativity",
        "flexibility",
    ],
    "expressive-connectors": [
        "relationship-orientation",
        "emotional-expression",
        "flexibility",
        "multitasking",
        "hospitality",
        "social-warmth",
        "expressive-communication",
        "impulsiveness",
        "social-interaction",
        "creativity",
    ],
} as const;

// ===== Mapping for easier validation =====
export const CategorySubcategoryEnumMap = {
    culture: CultureSubcategories,
    swot: SwotSubcategories,
} as const;
